# Pre-commit hooks configuration for Web Notes API
# Ensures code quality and consistency before commits

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        exclude: \.md$
      - id: end-of-file-fixer
        exclude: chrome-extension/.*
      - id: check-yaml
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=500']
      - id: debug-statements

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.13
        files: ^(backend|tests)/.*\.py$

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        files: ^(backend|tests)/.*\.py$
        args: ["--profile", "black"]

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        files: ^(backend|tests)/.*\.py$
        additional_dependencies:
          - flake8-docstrings
          - flake8-bugbear

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        files: ^backend/.*\.py$
        additional_dependencies:
          - types-requests
          - fastapi
          - uvicorn
        args: [--ignore-missing-imports]

# Configuration for specific tools
exclude: |
  (?x)^(
    \.venv/.*|
    chrome-extension/.*|
    \.git/.*|
    __pycache__/.*|
    .*\.pyc|
    requirements/requirements\.lock
  )$